export enum EnvironmentEnum {
  DB_PATH = 'DB_PATH',
  FE_PATH = 'FE_PATH',
  SPOTIFY_REDIRECT_URI = 'SPOTIFY_REDIRECT_URI',
  SPOTIFY_AUTH_SCOPES = 'SPOTIFY_AUTH_SCOPES',
  DOWNLOADS_PATH = 'DOWNLOADS_PATH',
  FORMAT = 'FORMAT',
  DOWNLOAD_CONCURRENCY = 'DOWNLOAD_CONCURRENCY',
  YT_COOKIES_FILE = 'YT_COOKIES_FILE',
  YT_SKIP_BURST_LIMIT = 'YT_SKIP_BURST_LIMIT',
  YT_SKIP_BURST_COOLDOWN_MS = 'YT_SKIP_BURST_COOLDOWN_MS',
}
